### ISSUE TITLE
plese  HELP ME

### ISSUE THREAD

**Issue by tomatoees** [0xInfection/TIDoS-Framework#101]
File "modules/0x02-Scanning+Enumeration/ssltlsscan.py", line 15, in <module>
    import sslyze
ImportError: No module named sslyze

**Comment by hellresistor** [comment]
have tried this?

[https://pypi.org/project/sslyze/](url)

**Comment by VainlyStrain** [comment]
Hi! Did you install the requirements specified in the text file? If so, did you do so using the `--user` flag? If that is the case, since the tool is run as root, you may need to add your local lib path to the global $PATH variable.

Greetings!
