### ISSUE TITLE
Error - During initial install in kali linux

### ISSUE THREAD

**Issue by filebe777** [0xInfection/TIDoS-Framework#105]
Preparing for installation...
Finalising options...
Traceback (most recent call last):
  File "install", line 18, in <module>
    install()   # run the install
  File "setup/install.py", line 59, in install
    raw_input(G+"\nPress 'Enter' to start the installation...")
NameError: name 'raw_input' is not defined
┌─[✗]─[root@kali]

**Comment by VainlyStrain** [comment]
Hi!

Which Python version are you running TIDoS with? TIDoS < 2.0 are only working with Python2.

Cheers!
