### ISSUE TITLE
Tidos doesn't run - gives statck trace. 

### ISSUE THREAD

**Issue by richdev135** [0xInfection/TIDoS-Framework#107]
Trying to run tidos gives me this error. 

`$ python3 tidos.py 
`Traceback (most recent call last):
`  File "tidos.py", line 14, in <module>
`    from core.tidos_main import *
`  File "/media/cinnamon-remix/OS/Linux/Dev/Tidos/tidos-framework/core/tidos_main.py", line 32, in <module>
`    from core.Auxillaries.auxil import *
`  File "/media/cinnamon-remix/OS/Linux/Dev/Tidos/tidos-framework/core/Auxillaries/auxil.py", line 20, in <module>
`    from encodeall import *
`  File "modules/0x05-Auxillaries+PF6/encodeall.py", line 15, in <module>
`    from cgi import escape
`ImportError: cannot import name 'escape' from 'cgi' (/usr/lib/python3.8/cgi.py)

**Comment by 0xInfection** [comment]
Use python2.
