### ISSUE TITLE
False [-] Site seems to be down...

### ISSUE THREAD

**Issue by ghost** [0xInfection/TIDoS-Framework#109]
![error](https://user-images.githubusercontent.com/66889345/86853979-deef6300-c0b7-11ea-8b0e-b71bf7d8856f.png)

If there is `/index.php' or `login.php` or extension after .domain it will give false site down to.
Error to this is in line 40 in inputin.py, to avoid this you can replace 
```
if str(web).endswith('/'):
            web = po[:-1]
            po = po[:-1]
```
with 
```
if "/" in po:
            po = po.split("/")[0]
```

**Comment by VainlyStrain** [comment]
Added to the 2.0 checklist, thanks for reporting!

**Comment by VainlyStrain** [comment]
This should be fixed in the latest release. I am closing this issue now. If you encounter more problems, be sure to let me know, and I'll reopen it. Greetings!
