### ISSUE TITLE
Please help with these errors while installing TIDOs-Framwork on kalilinux

### ISSUE THREAD

**Issue by krish2001na** [0xInfection/TIDoS-Framework#113]
Hello there,
I have followed every step described on this site, however i am getting follwoing error and the installation is not successfull. 
My Kali version is "Linux kali 5.7.0-kali1-amd64 #1 SMP Debian 5.7.6-1kali2 (2020-07-01) x86_64 GNU/Linux"

Please help me with this error message

![TIDOs-Framework installation error](https://user-images.githubusercontent.com/69446064/92210280-6e1cbb00-ee5c-11ea-9469-7f0615afd4a5.png)
ASLO below is the text form of the same error:

root@kali:~/Downloads/tidos-framework# python tidos.py 
Traceback (most recent call last):
  File "tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/root/Downloads/tidos-framework/core/tidos_main.py", line 35, in <module>
    from core.Footprinting.footprint import *
  File "/root/Downloads/tidos-framework/core/Footprinting/footprint.py", line 19, in <module>
    from core.Footprinting.Active_Recon.activeo import *
  File "/root/Downloads/tidos-framework/core/Footprinting/Active_Recon/activeo.py", line 21, in <module>
    from grabhead import *
  File "modules/0x01-OSINT+Footprinting/0x02-ActiveReconnaissance/grabhead.py", line 12, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'

Thank you,

**Comment by VainlyStrain** [comment]
Hi! Which Python version, and which TIDoS version are you running? If you're running TIDoS < 2.0 with Python3, this is normal, because it is Python2 only, and Python3 has changed the name of urllib2.

Try the following:

* run TIDoS < 2.0 with python2
* switch to the dev branch and run TIDoS 2.0 with Python3.

Cheers!

**Comment by krish2001na** [comment]
Thank you dear Brother,
I am happy to receive your email and really impressed by your professional help in solving my problem
It is good that you pointed out V.2 in dev folder. I did not know about that.
Know i will use V.2 and try out things.
By the way since i sent you this mail, i came across dockers and started learning about it and also could successfully installed V.1 on it and coudl also do some testing.
Wonderful piece of application is this TIDOS-Framework that you have written.
I congratulate you and your all friends for this.
Best of luck and Regards.

**Comment by krish2001na** [comment]
Thank you dear Brother,I am happy to receive your email and really impressed by your professional help in solving my problemIt is good that you pointed out V.2 in dev folder. I did not know about that.Know i will use V.2 and try out things.By the way since i sent you this mail, i came across dockers and started learning about it and also could successfully installed V.1 on it and coudl also do some testing.Wonderful piece of application is this TIDOS-Framework that you have written.I congratulate you and your all friends for this.Best of luck and Regards.


    On Saturday, 12 September 2020, 4:35:57 pm GMT+5:30, VainlyStrain <notifications@github.com> wrote:  
 
 


Hi! Which Python version, and which TIDoS version are you running? If you're running TIDoS < 2.0 with Python3, this is normal, because it is Python2 only, and Python3 has changed the name of urllib2.

Try the following:
   
   - run TIDoS < 2.0 with python2
   - switch to the dev branch and run TIDoS 2.0 with Python3.

Cheers!
