### ISSUE TITLE
Fail on tokenize.py

### ISSUE THREAD

**Issue by hellresistor** [0xInfection/TIDoS-Framework#120]
failing install requirements.txt

:)

```
 Downloading https://files.pythonhosted.org/packages/28/6c/640e3f5c734c296a7193079a86842a789edb7988dca39eab44579088a1d1/PyQt5-5.15.2.tar.gz (3.3MB)
    100% |################################| 3.3MB 282kB/s
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/usr/lib/python3.6/tokenize.py", line 452, in open
        buffer = _builtin_open(filename, 'rb')
    FileNotFoundError: [Errno 2] No such file or directory: '/tmp/pip-build-n4x155_0/PyQt5/setup.py'

    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /tmp/pip-build-n4x155_0/PyQt5/

```

**Comment by VainlyStrain** [comment]
Hi!

Do you have qt5 installed on your system? It is required by PyQt5.

Greetings!

**Comment by VainlyStrain** [comment]
According to [this](https://stackoverflow.com/questions/59711301/install-pyqt5-5-14-1-on-linux), it might be that you need to upgrade your pip. What version of pip do you have installed? It must be greater than 19.3.

Greetings!

**Comment by hellresistor** [comment]
> According to [this](https://stackoverflow.com/questions/59711301/install-pyqt5-5-14-1-on-linux), it might be that you need to upgrade your pip. What version of pip do you have installed? It must be greater than 19.3.
> 
> Greetings!

Thank you! 

Just need upgrade pip with `pip3 install --upgrade pip` and continues like a charm! 

Still w8 to the end :)

**Comment by VainlyStrain** [comment]
I'm glad it worked! Let me know when installation finished successfully.

**Comment by hellresistor** [comment]
Done! ;)

Found a little bug when addvictim but EMPTY argument. are return about an rm .

```
tid2 > vicadd
 [?] Does this website use SSL? (y/n) :> n
 [?] Does the site use a custom port? (enter if not) :>
 [*] Checking server status...
 [+] Site seems to be up...|
 [+] IP Detected :|0.0.0.0|

rm: invalid option -- 'l'
Try 'rm --help' for more information.
 [?] Enter username (leave blank if none):
```

**Comment by VainlyStrain** [comment]
hmm ok, thought I've fixed that one :) Will push a fix in the coming hours, thanks for reporting!

**Comment by hellresistor** [comment]
when trying turn tor on.

tid2 > tor on
 [-] Tor service not running. Aborting...
 [?] Do you want to start the Tor service? (enter if not) :> y
 [+] Tor service successfully started.|
 [-] Tor service not running. Aborting...
 [?] Do you want to start the Tor service? (enter if not) :> y
 [+] Tor service successfully started.|
 [-] Tor service not running. Aborting...
 [?] Do you want to start the Tor service? (enter if not) :>

**Comment by VainlyStrain** [comment]
The tor command is working for me.

```
 tid2 > tor on
 [-] Tor service not installed or running. Aborting...
 [?] Do you want to start the Tor service? (enter if not) :> y
 [+] Tor service successfully started.|
 [+] Tor|ON|
```
What happens in the background here is `systemctl start tor`. Maybe there is a problem running that command? Do you have the `tor` package installed?

**Comment by VainlyStrain** [comment]
What does `systemctl status tor` show?

**Comment by hellresistor** [comment]
check! tor installed and running

```
$ sudo systemctl status tor
● tor.service - Anonymizing overlay network for TCP (multi-instance-master)
   Loaded: loaded (/lib/systemd/system/tor.service; enabled; vendor preset: enabled)
   Active: active (exited) since Thu 2020-12-17 19:39:35 UTC; 2h 14min ago
 Main PID: 7941 (code=exited, status=0/SUCCESS)
    Tasks: 0 (limit: 9470)
   CGroup: /system.slice/tor.service

Dec 17 19:39:35 tester18 systemd[1]: Starting Anonymizing overlay network for TCP (multi-instance-master)...
Dec 17 19:39:35 tester18 systemd[1]: Started Anonymizing overlay network for TCP (multi-instance-master).
```

**Comment by VainlyStrain** [comment]
The log shows `active (exited)`, meaning that it is currently not running. TIDoS is waiting for it to be `active (running)`. Maybe there was an issue starting the service?

**Comment by hellresistor** [comment]
maybe a confused testsystem (many test script in their heart). I will set new server with ubuntu 20 server. Will not be ready today.
I will close and back later. o/
