### ISSUE TITLE
pls help me: tid2 > attack  [-] No module loaded.

### ISSUE THREAD

**Issue by phanthuthao** [0xInfection/TIDoS-Framework#123]
tid2 > attack
 [-] No module loaded.

**Comment by VainlyStrain** [comment]
Hi!

Before you can use the `attack` command, you have to set a victim (or multiple), and load a module. To do this, use the `vicadd` and `load` commands. To get help with commands, use the `?` command.

Greetings!

**Comment by 0xInfection** [comment]
Low quality issue with almost no context, closing this. Thanks @VainlyStrain for the response!
