### ISSUE TITLE
i made a working gui for your docker container

### ISSUE THREAD

**Issue by g33kz4su** [0xInfection/TIDoS-Framework#125]
Check out my edited version of TIDoS-Framework Dockerfile. It has a working gui in the container. :)

(make sure weston & x11docker is installed, and ofc docker is working)
```sh
	docker build -f ./Dockerfile -t tidos:tidos-framework .
```
```sh
	x11docker --wayland --wm --clipboard --sudouser --shell="bash" --env="SHELL=/bin/bash" --init=systemd --  --  tidos:tidos-framework konsole
```

x11docker has a pre defined sudo passwd = ``x11docker``

once in the container in konsole terminal run:
```sh
	cd /opt/TIDoS && python3 tidv2
```

it opens TIDoS's gui window

**OPTIONAL**
You will be asked for the path of Vailyn.
Git clone it while in the container and build/install.
Relaunch TIDoS and give the Vailyn path when asked by tidv2.
[Dockerfile.txt](https://github.com/0xInfection/TIDoS-Framework/files/5753189/Dockerfile.txt)
![x1docker_TIDoS](https://user-images.githubusercontent.com/76766272/103333340-84114580-4a22-11eb-8b58-01d61a9a5f30.png)

credit goes to MrGFY (my true handle, hope you guys like it.)

**Comment by VainlyStrain** [comment]
Hi!

Thanks for your contribution! I'm going to test this later in the day, and apply the changes if it works!

Greetings!

**Comment by VainlyStrain** [comment]
Hi! I don't know if my setup is broken, but I am unable to execute attacks with the GUI in the Docker container. Running the exact commands as above, it successfully starts the GUI. I can configure the attack, but when attacking, `pkexec` fails for me :thinking: 

I tested it on an Ubuntu 20 LTS VM, since my main OS doesn't support Docker.

**Comment by g33kz4su** [comment]
Hi, I'm on arco xfce edition, and it all works for me. I wish I knew more about pkexec to help.

**Comment by galiehneh** [comment]
Hi, im facing this kind of error, what am i missing? i installed "TIDoS-Framework dependencies" already

````
root@31e0d1e80d38:/# cd /opt/TIDoS && python3 tidv2
qt.qpa.xcb: could not connect to display 
qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.

Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.

Aborted
````

**Comment by ghost** [comment]
> Hi, im facing this kind of error, what am i missing? i installed "TIDoS-Framework dependencies" already
> 
> ```
> root@31e0d1e80d38:/# cd /opt/TIDoS && python3 tidv2
> qt.qpa.xcb: could not connect to display 
> qt.qpa.plugin: Could not load the Qt platform plugin "xcb" in "" even though it was found.
> This application failed to start because no Qt platform plugin could be initialized. Reinstalling the application may fix this problem.
> 
> Available platform plugins are: eglfs, linuxfb, minimal, minimalegl, offscreen, vnc, wayland-egl, wayland, wayland-xcomposite-egl, wayland-xcomposite-glx, webgl, xcb.
> 
> Aborted
> ```

try installing this https://github.com/xkbcommon/libxkbcommon
also try your pkg manager, i.e. ``sudo apt search libxkbcommon`` or ``yay -Ss xkb`` or any combination like that, and you'll find what you need.
