### ISSUE TITLE
sshbrute don't do anything

### ISSUE THREAD

**Issue by elig0n** [0xInfection/TIDoS-Framework#131]
**Describe the bug**
when running sshbrute against valid ip and port the list of attempts is displayed but no connection attempts are detected via either wireshark nor ssh authentication logs.

**To Reproduce**
```
vicadd --ip 192.168.14.1
load sshbrute
attack
```

**Actual behavior**
a lot of `[!] Checking X and Y...` lines scrolling fast but no actual attempts are detected

**Specs (please complete the following information):**
 - OS: Arch
 - Python Version 3.9
 - TIDoS Version git

**Comment by 0xInfection** [comment]
Are you sure you have the pexpect library installed? I'm not quite sure what is the issue here but looking at the code I can fairly confidently say that the script should attempt to connect to the server.

**Comment by elig0n** [comment]
I found two caveats. One is that the user prompted port is not even used, for which I published [this PR](https://github.com/0xInfection/TIDoS-Framework/pull/133) and second that I should have run packet capture program on interface `lo` 😀
