### ISSUE TITLE
[Question] => What issues remain in the migration to Python 3?

### ISSUE THREAD

**Issue by cclauss** [0xInfection/TIDoS-Framework#48]
It might be helpful to have one issue that documents the remaining issues.
- [ ] * imports are blocking linter visibility of [instances of __raw_input()__](https://github.com/0xInfection/TIDoS-Framework/search?q=raw_input).

**Comment by 0xInfection** [comment]
As I have said before, I am not presently concerned about this. The whole code is gonna be changed, so I see no reason working on this potentially discardable code.
 : )
