### ISSUE TITLE
Exception after shutdown

### ISSUE THREAD

**Issue by cbayonag** [0xInfection/TIDoS-Framework#55]
the framework was running at the time I put on sleep the vm and restarted afterwards ,  i installed tidos on a kalivm after that i have subsequent unhandled runtime exception.

`
   =====================
    D N S   L 0 0 K U P
   =====================

There was an error getting results

 [+] DNS Records
 [-] Unhandled runtime exception while execution...
 [-] Returning back to main menu...
`

``

**Comment by 0xInfection** [comment]
Well you're most probably not connected to the internet.

**Comment by cbayonag** [comment]
Thanks for the rapid response but Im already connected,  other modules like vulnerability enumeration works but these not.

**Comment by 0xInfection** [comment]
Is that so. well I think I'd have to reopen this.

**Comment by 0xInfection** [comment]
I made some commits, can you confirm they are working?
