### ISSUE TITLE
[Feature Request] Docker Container

### ISSUE THREAD

**Issue by meigea** [0xInfection/TIDoS-Framework#61]
Is there a docker container made , i haven't a os with ubunut or debian, and there are some many errors with installing this programe with centos7.

could some one share a docker container please?

**Comment by arkwrn** [comment]
You can use this https://hub.docker.com/r/tuantakoer/tidos-framework

**Comment by 0xInfection** [comment]
Debian is the recommended distro for TIDoS. There isn't a dockerfile ready for this version but I am to shorty release v2 which will include everything. Heads up and keep a watch.

**Comment by 0xInfection** [comment]
There isn't a Docker image for this version to TIDoS. However, I am shortly about to release v2 of this framework which will include everything. I'll keep this issue open untill there is a proper Dockerfile.

**Comment by 0xInfection** [comment]
Resolved in #75.
