### ISSUE TITLE
[Bug] => ModuleNotFound libmariadbclient

### ISSUE THREAD

**Issue by aligrt** [0xInfection/TIDoS-Framework#66]
following error while running tidos

```
root@kali:~/tidoS-framework# tidos
Traceback (most recent call last):
  File "/opt/tidos/tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/opt/tidos/core/tidos_main.py", line 37, in <module>
    from core.Vulnlysis.vuln import *
  File "/opt/tidos/core/Vulnlysis/vuln.py", line 17, in <module>
    from core.Vulnlysis.Oth_Bugs.othbugs import *
  File "/opt/tidos/core/Vulnlysis/Oth_Bugs/othbugs.py", line 22, in <module>
    from sqlbrute import *
  File "modules/0x03-Vulnerability+Analysis/0x03-OtherWebBugs/sqlbrute.py", line 12, in <module>
    import _mysql
  File "build/bdist.linux-x86_64/egg/_mysql.py", line 7, in <module>
  File "build/bdist.linux-x86_64/egg/_mysql.py", line 6, in __bootstrap__
ImportError: libmariadbclient.so.18: cannot open shared object file: No such file or directory

I have also tried with python3 tidos.py but following error received

Traceback (most recent call last):
  File "tidos.py", line 14, in <module>
    from core.tidos_main import *
  File "/root/tidoS-framework/core/tidos_main.py", line 35, in <module>
    from core.Footprinting.footprint import *
  File "/root/tidoS-framework/core/Footprinting/footprint.py", line 19, in <module>
    from core.Footprinting.Active_Recon.activeo import *
  File "/root/tidoS-framework/core/Footprinting/Active_Recon/activeo.py", line 21, in <module>
    from grabhead import *
  File "modules/0x01-OSINT+Footprinting/0x02-ActiveReconnaissance/grabhead.py", line 12, in <module>
    import urllib2
ModuleNotFoundError: No module named 'urllib2'
```
any suggestion please. I am using Kali 2019.1a

**Comment by 0xInfection** [comment]
You can do `sudo apt install libmariadbclient*`, which will fix the error. I'll add this into the setup file.

**Comment by mikael-jansson** [comment]
Hi @0xInfection , I get the sam e error as @aligrt and when I try `apt-get install libmariadbclient18` I get the following error:

`Package libmariadbclient18 is not available, but is referred to by another package.
This may mean that the package is missing, has been obsoleted, or
is only available from another source
However the following packages replace it:
  libmariadb3

E: Package 'libmariadbclient18' has no installation candidate
`
It suggests installing libmariadb3 instead, which I already have installed (also tried to reinstall it) without success.

I am running on:
`Linux ampete 4.19.0-kali4-amd64 #1 SMP Debian 4.19.28-2kali1 (2019-03-18) x86_64 GNU/Linux`

Any suggestions how to solve this?

**Comment by Cr0wv** [comment]
ImportError: libmariadbclient.so.18: cannot open shared object file: No such file or directory

**Comment by 0xInfection** [comment]
Hi @mikael-jansson, are you sure that you have your `apt update` already done? My distro is same as yours and I cannot reproduce this.

@Cr0wv, follow what I have given, it will solve your problem easily.

**Comment by mikael-jansson** [comment]
@0xInfection , yes I ran apt update several times and also search for the package libmariadbclient18 and it doesn´t exist. 

Could it be that my distro is missing a apt source link so it doesn´t find it?

**Comment by 0xInfection** [comment]
Fixed in b15de6b.

**Comment by 0xInfection** [comment]
@mikael-jansson have a look [here](https://stackoverflow.com/questions/51110986/libmariadbclient-dev-install-error-depends-libmariadbclient18) might help you out. In the meantime, I have pushed a general fix.

**Comment by 0xInfection** [comment]
Hi @mikael-jansson, I observed that almost everyone on latest versions of distros was facing this issue so I decided to dig it out. It was actually a deprecated library function which I had initially used in my code. So I found a work around and I rewrote the entire module with another library. I think this should work now. :)

**Comment by mikael-jansson** [comment]
Hi @0xInfection, the fresh install after your modifications made it work :-)

You are awesome @0xInfection! I have never met anyone that addresses AND fixes an issue with this speed of lightning before. Thank you so much
