### ISSUE TITLE
[Bug] ModuleNotFoundError: No module named 'core'

### ISSUE THREAD

**Issue by aligrt** [0xInfection/TIDoS-Framework#73]
while updating following error received
root@kali:~/tidos-Framework/tools# python tidos_updater.py 
Traceback (most recent call last):
  File "tidos_updater.py", line 18, in <module>
    from core.Core.colors import *
ImportError: No module named core.Core.colors

root@kali:~/tidos-Framework/tools# python3 tidos_updater.py 
Traceback (most recent call last):
  File "tidos_updater.py", line 18, in <module>
    from core.Core.colors import *
ModuleNotFoundError: No module named 'core'

any suggestions?

**Comment by 0xInfection** [comment]
Fixed in f11be41.
