### ISSUE TITLE
API key - CENSYS

### ISSUE THREAD

**Issue by Kavxhub** [0xInfection/TIDoS-Framework#74]
Hi,

I put my own API key in "API_key.py" but when I use the module it still importing the default API keys.

Any help ?

TY

**Comment by 0xInfection** [comment]
Hi,

Did you put your Censys Secret and Censys UID keys within [this file](https://github.com/0xInfection/TIDoS-Framework/blob/master/files/API_KEYS.py)? Can put the actual message what it displays here?

**Comment by Kavxhub** [comment]
Hi 0xInfection,

I put my Censys Secret and Censys UID in the file you mentionned.
See below the message that was display :

![mstsc_dLfdNNFaat](https://user-images.githubusercontent.com/50601842/57672872-93295280-75b5-11e9-8b3c-0419ce623684.png)

Installing it again solved my problem. 

Thank you
