### ISSUE TITLE
Ping check -> Outbound Query Exception

### ISSUE THREAD

**Issue by DavixonPt** [0xInfection/TIDoS-Framework#81]
Everytime I try to ping check I get this error: Outbound Query Exception!

Anyone any idea why this is and how to fix it?

Thanks in advance

**Comment by Swastik2561** [comment]
API conflicting with the Outbound Query Exception was changed.

**Comment by 0xInfection** [comment]
Hi, thanks for everything. However, this is a big project and I am too strapped up on time to work on this. I am planning to rewrite the entire framework, in a way it becomes a full featured pentesting toolkit. Thank you for your contributions tho. :)

**Comment by Swastik2561** [comment]
Sure Man would love to.
