### ISSUE TITLE
pip install -r requirements.txt error on Mac OS

### ISSUE THREAD

**Issue by M0dred** [0xInfection/TIDoS-Framework#85]
Collecting MySQL-python (from mysql->-r requirements.txt (line 18))
  Downloading https://files.pythonhosted.org/packages/a5/e9/51b544da85a36a68debe7a7091f068d802fc515a3a202652828c73453cad/MySQL-python-1.2.5.zip (108kB)
     |████████████████████████████████| 112kB 7.0MB/s 
    ERROR: Complete output from command python setup.py egg_info:
    ERROR: sh: mysql_config: command not found
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/tmp/pip-install-fnhp_Q/MySQL-python/setup.py", line 17, in <module>
        metadata, options = get_config()
      File "setup_posix.py", line 43, in get_config
        libs = mysql_config("libs_r")
      File "setup_posix.py", line 25, in mysql_config
        raise EnvironmentError("%s not found" % (mysql_config.path,))
    EnvironmentError: mysql_config not found
    ----------------------------------------
ERROR: Command "python setup.py egg_info" failed with error code 1 in /private/tmp/pip-install-fnhp_Q/MySQL-python/

**Comment by johntyty912** [comment]
https://stackoverflow.com/questions/25459386/mac-os-x-environmenterror-mysql-config-not-found
