### ISSUE TITLE
Installing sslyze is not working

### ISSUE THREAD

**Issue by Hacker5preme** [0xInfection/TIDoS-Framework#86]
I tried to install sslyze through the install programm, and also by myslef trying different versions of sslyze, but it is not working.

Error:
ERROR: Could not find a version that satisfies the requirement nassl<1.2.0,>=1.1.0 (from sslyze) (from versions: 0.13.4.win32, 0.13.1, 0.13.2, 0.13.4, 0.13.5, 0.13.6, 0.13.7, 0.14.0, 0.14.1, 0.14.2, 0.15.0, 0.15.1, 0.16.0, 0.16.1, 0.16.2, 0.16.3, 0.17.0, 1.0.1, 1.0.2, 1.0.3)
ERROR: No matching distribution found for nassl<1.2.0,>=1.1.0 (from sslyze)

**Comment by 0xInfection** [comment]
Have a look at #28.
