### ISSUE TITLE
no module named xmpp

### ISSUE THREAD

**Issue by shanow7** [0xInfection/TIDoS-Framework#94]
when I've used 
sudo apt-get install libncurses5 libxml2 nmap tcpdump libexiv2-dev build-essential python-pip python-xmpp

and then

pip2 install -r requirements.txt
python2 tidos.py or ./tidos.py

I have this
![image](https://user-images.githubusercontent.com/37192410/72287442-5bdcdb00-3647-11ea-9e37-5735023de395.png)

**Comment by Jflye** [comment]
I cloned the repository here for xmpp and installed it, worked like a charm. Had the same issue  before that.
`https://github.com/normanr/xmpppy`

**Comment by shanow7** [comment]
I've used install xmpppy and it's work but some moduls at passive recon dosn't work f.g. nr 11, 12 19

**Comment by Jflye** [comment]
I've noticed that too, I'm not sure which ones but there's not only in the passive recon, even some other vuln scans just auto quit and send you back to the first screen again. Strange behavior.

**Comment by vincegremillion** [comment]
> I cloned the repository here for xmpp and installed it, worked like a charm. Had the same issue before that.
> `https://github.com/normanr/xmpppy`
I used your clone, but still, have an issue - won't start tidos, just vomits this code used in the example.

**Comment by subbusainath** [comment]
still am getting No module named xmpp  Even in have tried with installing using pip in terminal and i have also tried with cloning still getting || i am in uttermost anger |||

**Comment by th3cyb3rc0p** [comment]
> still am getting No module named xmpp Even in have tried with installing using pip in terminal and i have also tried with cloning still getting || i am in uttermost anger |||

use

pip install xmpppy
