### ISSUE TITLE
[Announcement] New release

### ISSUE THREAD

**Issue by 0xInfection** [0xInfection/TIDoS-Framework#99]
This is just a heads up for the userbase of TIDoS that this framework has got itself another co-lead developer @VainlyStrain. He will be contributing towards the new release of 2.0 with better features and upgrades. Together we will also be bringing newer modules and functionalities to this framework, and there cannot be a better news than this. Again, many thanks to @VainlyStrain!

Stay tuned and thanks for your support!

Bests.

**Comment by q2dg** [comment]
It would be great if this project finally get rid of Python2.

**Comment by VainlyStrain** [comment]
There is already a test version of 2.0 in the dev branch, completely in Python 3. Hope you'll like it :)
Bests

**Comment by VainlyStrain** [comment]
TIDoS 2.0 is out as a beta release. Please report any bugs using the `beta-2.0` label. Greetings!

**Comment by VainlyStrain** [comment]
TIDoS 2.0 has arrived on master. I'll make some final adjustments & wait for some feedback, then I'll define the first 2.0 release.
